source 'http://rubygems.org'

gem 'rails', '~> 5.2.4.1'
#gem 'ios-checkboxes', '0.2.1'
gem 'jquery-rails'
gem 'ruby-stemmer', :require => 'lingua/stemmer'
gem 'text', :require => 'text/white_similarity'
gem 'thin'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'execjs'
gem 'therubyracer', :platforms => :ruby

