source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'ios-checkboxes'
gem 'jquery-rails'
gem 'ruby-stemmer', :require => 'lingua/stemmer'
gem 'text', :require => 'text/white_similarity'

gem 'thin'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '3.2.5'
  gem 'coffee-rails'
  gem 'uglifier'
end

